import { expect, test } from '@playwright/test'

async function login(page: import('@playwright/test').Page, identity = 'browser-user', password = 'BrowserPassword123', returnTo = '/') {
  await page.goto(`/login/?returnTo=${encodeURIComponent(returnTo)}`)
  await page.locator('#identity').fill(identity)
  await page.locator('#password').fill(password)
  await page.locator('#authForm').getByRole('button', { name: '登录' }).click()
  await expect(page).toHaveURL(new RegExp(returnTo === '/' ? '/$' : returnTo.replaceAll('/', '\\/')))
}

test('card opens an internal, reload-safe detail page with an explicit GitHub handoff', async ({ page }) => {
  await page.goto('/')
  const card = page.locator('.dsh-card').first()
  await expect(card).toBeVisible()
  const title = await card.locator('.dsh-card-title').textContent()
  await card.focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/plugin\/\?id=/)
  await expect(page.locator('.dsh-detail-summary h1')).toHaveText(title || '')
  await expect(page.getByRole('heading', { name: '当前版本更新' })).toBeVisible()
  await expect(page.locator('.dsh-release-notes').first()).toContainText('traceable browser-test release')
  const github = page.getByRole('link', { name: /前往 GitHub/ })
  await expect(github).toHaveAttribute('target', '_blank')
  await expect(github).toHaveAttribute('rel', /noopener/)
  await page.reload()
  await expect(page.locator('.dsh-detail-summary h1')).toHaveText(title || '')
  await page.goBack()
  await expect(page).toHaveURL(/127\.0\.0\.1:4273\/$/)
})

test('login returns to the plugin and enables persisted user actions', async ({ page }) => {
  await page.goto('/')
  await page.locator('.dsh-card').first().click()
  const detailUrl = page.url()
  await page.getByRole('button', { name: /^收藏$/ }).click()
  await expect(page).toHaveURL(/\/login\//)
  await page.locator('#identity').fill('browser-user')
  await page.locator('#password').fill('BrowserPassword123')
  await page.locator('#authForm').getByRole('button', { name: '登录' }).click()
  await expect(page).toHaveURL(detailUrl)
  await page.getByRole('button', { name: /^收藏$/ }).click()
  await expect(page.getByRole('button', { name: '已收藏' })).toBeVisible()

  await page.locator('#reviewForm textarea').fill('在当前公开 Revision 上完成了真实浏览器验证。')
  await page.locator('#reviewForm').getByRole('button', { name: '发布评价' }).click()
  await expect(page.locator('.dsh-review-list')).toContainText('真实浏览器验证')

  await page.getByRole('button', { name: '加入合集' }).click()
  await page.locator('#quickCollectionForm input[name="name"]').fill('浏览器测试合集')
  await page.locator('#quickCollectionForm').getByRole('button', { name: '创建合集' }).click()
  await expect(page.locator('.dsh-dialog.open')).toHaveCount(0)

  await page.locator('#dshAccountButton').click()
  await page.getByRole('button', { name: '设备会话' }).click()
  await expect(page.locator('#dshDialogBody')).toContainText('当前会话')
})

test('catalog search and real facets are reflected in the URL', async ({ page }) => {
  await page.goto('/')
  const firstTitle = await page.locator('.dsh-card-title').first().textContent()
  await page.locator('input[name="q"]').fill(firstTitle || '')
  await page.getByRole('button', { name: '应用筛选' }).click()
  await expect(page).toHaveURL(/\?q=/)
  await expect(page.locator('.dsh-card')).toHaveCount(1)
  await page.locator('select[name="surface"]').selectOption({ index: 1 })
  await page.getByRole('button', { name: '应用筛选' }).click()
  await expect(page).toHaveURL(/surface=/)
})

test('catalog and detail remain usable on a narrow mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.dsh-card').first()).toBeVisible()
  await page.locator('.dsh-card').first().click()
  await expect(page.getByRole('link', { name: /前往 GitHub/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('activity filters expose platform and plugin release-note snapshots', async ({ page }) => {
  await page.goto('/?view=activity')
  await expect(page.getByRole('heading', { name: '更新动态' })).toBeVisible()
  await page.getByRole('button', { name: '平台更新' }).click()
  await expect(page.locator('.dsh-activity-list')).toContainText('DSH Creative Workshop v1.1.3')
  await expect(page.locator('.dsh-activity-item details')).toContainText('目录同步稳定性修复')
  await page.getByRole('button', { name: '插件更新' }).click()
  await expect(page.locator('.dsh-activity-item').first()).toContainText('traceable browser-test release')
})

test('a user can change their username with password verification', async ({ page }) => {
  await login(page, 'browser-profile', 'BrowserProfilePassword123')
  await page.locator('#dshAccountButton').click()
  await page.getByRole('button', { name: '账号名', exact: true }).click()
  await page.locator('#changeUsernameForm input[name="username"]').fill('browser-renamed')
  await page.locator('#changeUsernameForm input[name="currentPassword"]').fill('BrowserProfilePassword123')
  await page.locator('#changeUsernameForm').getByRole('button', { name: '确认修改' }).click()
  await expect(page.locator('#dshAccountButton')).toContainText('browser-renamed')
  await expect(page.locator('#dshDialogBody')).toContainText('下次可修改时间')
})

test('homepage shows live presence and a signed-in user can publish discussions', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('#dshPresenceBadge')).toHaveText(/当前在线 \d+/)

  await login(page)
  await page.goto('/?view=discussions')
  await page.locator('#discussionForm input[name="title"]').fill('浏览器端社区讨论验证')
  await page.locator('#discussionForm textarea[name="body"]').fill('这是一条通过真实浏览器流程创建并可在刷新后读取的讨论内容。')
  await page.locator('#discussionForm').getByRole('button', { name: '发布主题' }).click()
  await expect(page).toHaveURL(/\/discussion\/\?id=/)
  await expect(page.locator('.dsh-thread-detail h1')).toHaveText('浏览器端社区讨论验证')
  await page.locator('#replyForm textarea[name="body"]').fill('浏览器端回复也已接入真实后端。')
  await page.locator('#replyForm').getByRole('button', { name: '发布回复' }).click()
  await expect(page.locator('.dsh-review-list')).toContainText('浏览器端回复也已接入真实后端')
  await page.reload()
  await expect(page.locator('.dsh-thread-detail h1')).toHaveText('浏览器端社区讨论验证')
})

test('a user can publish a collection, discover it in the square and clone it', async ({ page }) => {
  await login(page)
  await page.locator('#dshAccountButton').click()
  await page.getByRole('button', { name: '合集', exact: true }).click()
  await page.locator('#createCollectionForm input[name="name"]').fill('浏览器公开合集')
  await page.locator('#createCollectionForm input[name="description"]').fill('用于验证合集广场、详情和复制流程。')
  await page.locator('#createCollectionForm select[name="visibility"]').selectOption('public')
  await page.locator('#createCollectionForm').getByRole('button', { name: '创建空合集' }).click()
  await expect(page.locator('[data-collection-name][value="浏览器公开合集"]')).toBeVisible()
  await page.goto('/collections/')
  const collection = page.locator('[data-public-collection]').filter({ hasText: '浏览器公开合集' }).first()
  await expect(collection).toBeVisible()
  await collection.click()
  await expect(page.locator('.dsh-collection-hero h1')).toHaveText('浏览器公开合集')
  await page.getByRole('button', { name: '复制到我的合集' }).click()
  await expect(page.locator('.dsh-toast')).toContainText('已复制为你的私有合集')
})

test('administrator overview and community governance are available on desktop and mobile', async ({ page }) => {
  await login(page, 'browser-admin', 'BrowserAdminPassword123', '/admin/')
  await expect(page.getByRole('heading', { name: '运行总览' })).toBeVisible()
  await expect(page.locator('.presence-stat')).toContainText('当前在线')
  await page.locator('[data-view="community"]').click()
  await expect(page.getByRole('heading', { name: '社区治理' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '内容治理' })).toBeVisible()
  await expect(page.locator('.community-panel').first()).toContainText('浏览器端社区讨论验证')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('heading', { name: '社区治理' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})
