import type { GitHubPluginRecord } from './auth-store.js'

type SeedInput = Omit<GitHubPluginRecord, 'id' | 'source' | 'securityReviewed'>

function plugin(input: SeedInput): GitHubPluginRecord {
  return {
    ...input,
    id: `github.${input.fullName.toLowerCase().replace(/[^a-z0-9]+/g, '.')}`,
    source: 'github-topic',
    securityReviewed: false,
  }
}

export const githubSeed: GitHubPluginRecord[] = [
  plugin({ fullName: 'titanwings/colleague-skill', name: 'colleague-skill', author: 'titanwings', description: '将冰冷的离别化为温暖的 Skill，欢迎加入数字生命 1.0。', url: 'https://github.com/titanwings/colleague-skill', stars: 21061, forks: 2033, language: 'Python', license: 'MIT', updatedAt: '2026-08-13T21:28:13Z', pushedAt: '2026-08-13T15:00:28Z', topics: ['agent-skills','deepseek-harness','dsh-plugin'], kind: 'skill-pack', surfaces: ['web','headless'] }),
  plugin({ fullName: 'Devin-AXIS/iPolloWork', name: 'iPolloWork', author: 'Devin-AXIS', description: 'A next-generation AI workspace integrating DeepSeek Harness for subagent delegation.', url: 'https://github.com/Devin-AXIS/iPolloWork', homepage: 'https://www.ipollo.ai/', stars: 3562, forks: 774, language: 'HTML', updatedAt: '2026-08-13T21:33:32Z', pushedAt: '2026-08-13T20:15:08Z', topics: ['deepseek-harness','dsh-plugin','agent-collaboration'], kind: 'bundle', surfaces: ['web','headless'] }),
  plugin({ fullName: 'paean-ai/deeptide', name: 'deeptide', author: 'paean-ai', description: 'Built by DeepSeek, for DeepSeek — a Swift-native macOS coding agent.', url: 'https://github.com/paean-ai/deeptide', homepage: 'https://deeptide.sh', stars: 1015, forks: 133, language: 'Rust', license: 'MIT', updatedAt: '2026-08-13T21:17:21Z', pushedAt: '2026-07-08T09:37:30Z', topics: ['coding-agent','deepseek-harness','dsh-plugin','macos'], kind: 'bundle', surfaces: ['headless','tui'] }),
  plugin({ fullName: 'nutshellai-tech/mobius', name: 'mobius', author: 'nutshellai-tech', description: 'The first self-evolving open-source Agent OS connecting teams, agents, devices and compute.', url: 'https://github.com/nutshellai-tech/mobius', homepage: 'https://nutshellai-tech.github.io/mobius/', stars: 915, forks: 20, language: 'TypeScript', updatedAt: '2026-08-13T21:24:18Z', pushedAt: '2026-08-13T12:12:15Z', topics: ['dsh-plugin','dsh-plugins'], kind: 'bundle', surfaces: ['web','headless'] }),
  plugin({ fullName: 'liustack/modlens', name: 'modlens', author: 'liustack', description: 'The first vision plugin for DeepSeek Harness, providing OCR, layout and semantic evidence.', url: 'https://github.com/liustack/modlens', homepage: 'https://liustack.dev', stars: 703, forks: 22, language: 'TypeScript', license: 'MIT', updatedAt: '2026-08-13T21:32:09Z', pushedAt: '2026-08-13T19:34:36Z', topics: ['cordis','deepseek','dsh-plugin','ocr','vision'], kind: 'mcp-bundle', surfaces: ['web','headless'] }),
  plugin({ fullName: 'Anionex/agent-vision-toolkit', name: 'agent-vision-toolkit', author: 'Anionex', description: 'Vision toolkit for image Q&A, screenshot OCR, UI restoration and GUI automation.', url: 'https://github.com/Anionex/agent-vision-toolkit', homepage: 'https://agent-vision.anionex.me', stars: 522, forks: 22, language: 'Python', license: 'MIT', updatedAt: '2026-08-13T21:23:34Z', pushedAt: '2026-08-13T18:30:45Z', topics: ['computer-use','dsh-plugin','multimodal','vision'], kind: 'mcp-bundle', surfaces: ['web','headless'] }),
  plugin({ fullName: 'yejiming/MuseAI', name: 'MuseAI', author: 'yejiming', description: '创建你的 AI 角色并进入故事世界，让每一次互动留下长期羁绊。', url: 'https://github.com/yejiming/MuseAI', stars: 520, forks: 45, language: 'TypeScript', updatedAt: '2026-08-13T20:45:14Z', pushedAt: '2026-08-09T06:15:21Z', topics: ['agent','companion-ai','dsh-plugin'], kind: 'bundle', surfaces: ['web','headless'] }),
  plugin({ fullName: 'zhu1090093659/dsh-web-ui', name: 'dsh-web-ui', author: 'zhu1090093659', description: 'Plugin and skin collection for DSH Web UI with task board, Git graph and live token stats.', url: 'https://github.com/zhu1090093659/dsh-web-ui', stars: 508, forks: 22, language: 'TypeScript', updatedAt: '2026-08-13T21:24:37Z', pushedAt: '2026-08-13T17:34:26Z', topics: ['deepseek-harness','dsh','dsh-plugin','web-ui'], kind: 'web-ui', surfaces: ['web'] }),
  plugin({ fullName: 'cofy-x/axern', name: 'axern', author: 'cofy-x', description: 'Open-source sandboxes for AI agents, untrusted code execution and durable services.', url: 'https://github.com/cofy-x/axern', homepage: 'https://axern.cofy-x.space', stars: 249, forks: 6, language: 'Go', license: 'Apache-2.0', updatedAt: '2026-08-13T21:04:46Z', pushedAt: '2026-08-13T10:11:11Z', topics: ['agent-sandbox','deepseek-harness','dsh-plugin'], kind: 'bundle', surfaces: ['headless'] }),
  plugin({ fullName: 'ccch1mneyyy/dsh-cc-tui', name: 'dsh-cc-tui', author: 'ccch1mneyyy', description: 'Claude Code 风格全屏交互终端插件，提供状态行、思考流和上下文仪表。', url: 'https://github.com/ccch1mneyyy/dsh-cc-tui', stars: 198, forks: 5, language: 'TypeScript', license: 'BSD-3-Clause', updatedAt: '2026-08-13T21:26:00Z', pushedAt: '2026-08-13T21:01:52Z', topics: ['coding-agent','deepseek-harness','dsh-plugin','tui'], kind: 'tui', surfaces: ['tui','headless'] }),
  plugin({ fullName: 'Anionex/dsh-vision-toolkit', name: 'dsh-vision-toolkit', author: 'Anionex', description: 'DeepSeek Harness-native vision toolkit for OCR, UI restoration and screenshot testing.', url: 'https://github.com/Anionex/dsh-vision-toolkit', stars: 152, forks: 3, language: 'TypeScript', license: 'MIT', updatedAt: '2026-08-13T21:29:07Z', pushedAt: '2026-08-13T18:33:48Z', topics: ['deepseek-harness','dsh-plugin','ocr','vision-tools'], kind: 'mcp-bundle', surfaces: ['web','headless'] }),
  plugin({ fullName: 'omdsh-dev/DSH-better-sidebar', name: 'DSH-better-sidebar', author: 'omdsh-dev', description: '完整侧边栏工作台，支持扩展 Tab、文件编辑、终端、Git 与子代理。', url: 'https://github.com/omdsh-dev/DSH-better-sidebar', stars: 127, forks: 3, language: 'TypeScript', license: 'MIT', updatedAt: '2026-08-13T21:10:11Z', pushedAt: '2026-08-13T17:05:21Z', topics: ['deepseek-harness','dsh','dsh-plugin','sidebar'], kind: 'web-ui', surfaces: ['web'] }),
]
